import streamlit as st
import cv2
import numpy as np
from PIL import Image
import os


from src.vision import detect_part_in_image 
from src.ingest import query_local_documents


def inject_custom_css():
    st.markdown("""
    <style>
    .stApp {
        background-color: #070910;
        background-image: 
            linear-gradient(90deg, rgba(30, 30, 30, 0.05) 1px, transparent 1px), 
            linear-gradient(0deg, rgba(30, 30, 30, 0.05) 1px, transparent 1px);
        background-size: 40px 40px;
    }

    [data-testid="stVerticalBlock"] {
        background: rgba(255, 255, 255, 0.05);
        padding: 25px;
        border-radius: 20px;
        border: 1px solid rgba(255, 255, 255, 0.1);
        backdrop-filter: blur(10px);
    }

    section[data-testid="stSidebar"] {
        background: linear-gradient(180deg, #1a1a2e 0%, #16213e 100%);
    }

    h1, h2, h3 {
        background: linear-gradient(90deg, #00f2fe, #4facfe);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        font-weight: 800 !important;
    }

    div.stButton > button {
        background: linear-gradient(45deg, #f093fb 0%, #f5576c 100%) !important;
        color: white !important;
        border: none !important;
        border-radius: 50px !important;
    }
    
    .stInfo {
        background-color: #ff9a9e !important;
        color: #2d3436 !important;
        font-weight: bold;
    }
    </style>
    """, unsafe_allow_html=True)


st.set_page_config(
    page_title="ForgeAI - Industrial Intelligence",
    page_icon="⚙️",
    layout="wide"
)
inject_custom_css()


with st.sidebar:
    st.title("⚙️ ForgeAI Engine")
    st.markdown("---")
    st.subheader("System Status")
    
    st.write("🟢 Vision Core: Active")
    st.write("🟢 Knowledge Core: Active")
    
    app_env = os.getenv('APP_ENV', 'Windows Local (Air-Gapped)')
    st.info(f"Environment: {app_env}")
    
    st.markdown("---")
    st.markdown("### Active Dataset")
    st.caption("Target Domain: Fadal CNC Components")


st.title("ForgeAI: Industrial Operations Hub")
st.markdown("Integrating real-time vision analysis with semantic documentation.")
st.divider()

col1, col2 = st.columns([1, 1], gap="large")

with col1:
    st.header("📸 Real-Time Vision Inspection")
    uploaded_file = st.file_uploader("Upload Component Snapshot...", type=["jpg", "jpeg", "png"])
    
    detected_component = ""
    
    if uploaded_file is not None:
        image = Image.open(uploaded_file)
        with st.spinner("Processing image..."):
            processed_img, detected_component = detect_part_in_image(image)
        st.image(processed_img, use_container_width=True)
        st.metric(label="Detected", value=detected_component)
    else:
        st.info("Awaiting input stream...")

with col2:
    st.header("🧠 Technical RAG Interface")
    
    if "messages" not in st.session_state:
        st.session_state.messages = [{"role": "assistant", "content": "System ready. Ask any maintenance question."}]

    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    if detected_component and detected_component.strip():
        if "last_detected" not in st.session_state or st.session_state.last_detected != detected_component:
            st.session_state.last_detected = detected_component
            automated_prompt = f"Maintenance overview for: {detected_component}."
            st.session_state.messages.append({"role": "user", "content": automated_prompt})
            
            with st.spinner("Querying vector index..."):
                ai_response = query_local_documents(automated_prompt)
                st.session_state.messages.append({"role": "assistant", "content": ai_response})
                st.rerun()

    if prompt := st.chat_input("Ask a manual question..."):
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"): st.markdown(prompt)
        with st.spinner("Searching..."):
            response = query_local_documents(prompt)
        with st.chat_message("assistant"): st.markdown(response)
        st.session_state.messages.append({"role": "assistant", "content": response})
st.markdown("<style> .stApp { background-color: #f4f0e6; color: #3d332a; font-family: sans-serif; } div.stButton > button { background-color: #7c5c24; color: white; border-radius: 4px; border: none; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background-color: #f7f4ed; color: #2c2825; } div.stButton > button { background-color: #d4c5b9; color: #2c2825; border: 1px solid #b5a495; border-radius: 4px; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background-color: #f7f4ed; color: #2c2825; } div.stButton > button { background-color: #d4c5b9; color: #2c2825; border: 1px solid #b5a495; border-radius: 4px; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background-color: #0b132b; color: #ffffff; } div.stButton > button { background-color: #3a86ff; color: white; border-radius: 6px; border: none; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background-color: #08120d; color: #e0f2fe; } div.stButton > button { background-color: #10b981; color: #042f2e; border-radius: 6px; font-weight: bold; border: none; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background-color: #F4E7FB; color: #3a2e39; } div.stButton > button { background-color: #C8A8E9; color: #2d1e2f; border-radius: 6px; font-weight: bold; border: 1px solid #E3AADD; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background-color: #F3DCDC; color: #2d2323; } div.stButton > button { background-color: #F5BCBA; color: #2d2323; border-radius: 6px; font-weight: bold; border: 1px solid #E3AADD; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background-color: #C3C7F3; color: #25283d; } div.stButton > button { background-color: #F4E7FB; color: #25283d; border-radius: 6px; font-weight: bold; border: 1px solid #C8A8E9; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background-color: #FAF6F0; color: #2B2625; } [data-testid='stSidebar'] { background-color: #F0E9DF !important; } [data-testid='stSidebar'] * { color: #2B2625 !important; } h1, h2, h3, h4, h5, h6, p, span { color: #2B2625 !important; } div.stButton > button { background-color: #D4A373 !important; color: #FFFFFF !important; border-radius: 6px; font-weight: bold; border: none; } div[data-testid='stFileUploader'] { background-color: #FFFFFF !important; border: 1px solid #D4A373; border-radius: 8px; padding: 10px; } </style>", unsafe_allow_html=True) 
st.markdown("<style> [data-testid='stSidebar'] { background-color: #1a2238 !important; } [data-testid='stSidebar'] * { color: #ffffff !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background-color: #F7EBE8; color: #2B2625; } [data-testid='stSidebar'] * { color: #ffffff !important; } h1, h2, h3, h4, h5, h6 { color: #4A3B4C !important; } div.stButton > button { background-color: #D8A4B1 !important; color: #2B2625 !important; border-radius: 6px; font-weight: bold; border: none; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background-color: #F7EBE8; color: #2B2625; } [data-testid='stSidebar'] * { color: #ffffff !important; } h1, h2, h3, h4, h5, h6 { color: #4A3B4C !important; } div.stButton > button { background-color: #D8A4B1 !important; color: #2B2625 !important; border-radius: 6px; font-weight: bold; border: none; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background-color: #F7EBE8; color: #2B2625; } [data-testid='stSidebar'] * { color: #ffffff !important; } h1, h2, h3, h4, h5, h6 { color: #4A3B4C !important; } div.stButton > button { background-color: #D8A4B1 !important; color: #2B2625 !important; border-radius: 6px; font-weight: bold; border: none; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background-color: #1e1e2e; color: #cdd6f4; } [data-testid='stSidebar'] { background-color: #11111b !important; } [data-testid='stSidebar'] * { color: #cdd6f4 !important; } h1, h2, h3, h4, h5, h6 { color: #89b4fa !important; } div.stButton > button { background-color: #89b4fa !important; color: #11111b !important; border-radius: 6px; font-weight: bold; border: none; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background-color: #121212; color: #f3f4f6; } [data-testid='stSidebar'] { background-color: #18181b !important; } [data-testid='stSidebar'] * { color: #f3f4f6 !important; } h1, h2, h3, h4, h5, h6 { color: #1793d1 !important; } div.stButton > button { background-color: #1793d1 !important; color: #ffffff !important; border-radius: 6px; font-weight: bold; border: none; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background-color: #050505; color: #00f0ff; } [data-testid='stSidebar'] { background-color: #0b0c10 !important; border-right: 2px solid #ff007f; } [data-testid='stSidebar'] * { color: #00f0ff !important; } h1, h2, h3, h4, h5, h6 { color: #ff007f !important; text-shadow: 0 0 8px rgba(255,0,127,0.6); } div.stButton > button { background-color: #ff007f !important; color: #ffffff !important; border-radius: 0px; font-weight: bold; border: 1px solid #00f0ff; box-shadow: 0 0 8px rgba(0,240,255,0.5); } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background-color: #0f1012; color: #e4e4e7; } [data-testid='stSidebar'] { background-color: #16181b !important; border-right: 1px solid #27272a; } [data-testid='stSidebar'] * { color: #e4e4e7 !important; } h1, h2, h3, h4, h5, h6 { color: #f4f4f5 !important; letter-spacing: -0.5px; } div.stButton > button { background-color: #27272a !important; color: #f4f4f5 !important; border-radius: 8px; font-weight: 500; border: 1px solid #3f3f46; transition: all 0.2s ease; } div.stButton > button:hover { background-color: #3f3f46 !important; border-color: #52525b; } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input { background-color: #18191c !important; border: 1px solid #27272a !important; border-radius: 8px; color: #f4f4f5 !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background-color: #0f1012; color: #f4f4f5 !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #d4d4d8 !important; } h1, h2, h3, h4, h5, h6 { color: #ffffff !important; } [data-testid='stSidebar'] { background-color: #16181b !important; border-right: 1px solid #27272a; } [data-testid='stSidebar'] * { color: #f4f4f5 !important; } div.stButton > button { background-color: #27272a !important; color: #f4f4f5 !important; border-radius: 8px; font-weight: 500; border: 1px solid #3f3f46; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(135deg, #1f0b24 0%, #3a0ca3 50%, #480ca8 100%) !important; color: #f8f9fa !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #e2e8f0 !important; } h1, h2, h3, h4, h5, h6 { color: #f3c6ff !important; text-shadow: 0 2px 4px rgba(0,0,0,0.4); } [data-testid='stSidebar'] { background-color: #15071a !important; border-right: 1px solid #4a154b; } [data-testid='stSidebar'] * { color: #f8f9fa !important; } div.stButton > button { background: linear-gradient(90deg, #f72585 0%, #7209b7 100%) !important; color: #ffffff !important; border-radius: 8px; font-weight: bold; border: none; box-shadow: 0 4px 10px rgba(114,9,183,0.4); } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background-color: rgba(25, 10, 35, 0.8) !important; border: 1px solid #7209b7 !important; border-radius: 8px; color: #ffffff !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: radial-gradient(circle at center, #2e0249 0%, #11011c 50%, #000000 100%) !important; color: #ffffff !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #d1d5db !important; } h1, h2, h3, h4, h5, h6 { color: #e9d5ff !important; } [data-testid='stSidebar'] { background-color: #0f0117 !important; border-right: 1px solid #4c1d95; } [data-testid='stSidebar'] * { color: #ffffff !important; } div.stButton > button { background: linear-gradient(135deg, #c084fc 0%, #a855f7 100%) !important; color: #11011c !important; border-radius: 8px; font-weight: 600; border: none; } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background-color: rgba(30, 5, 50, 0.6) !important; border: 1px solid #6d28d9 !important; border-radius: 8px; color: #ffffff !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background-color: #0c0814 !important; background-image: linear-gradient(rgba(147, 51, 234, 0.07) 1px, transparent 1px), linear-gradient(90deg, rgba(147, 51, 234, 0.07) 1px, transparent 1px) !important; background-size: 30px 30px !important; color: #ffffff !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #e2e8f0 !important; } h1, h2, h3, h4, h5, h6 { color: #f3c6ff !important; } [data-testid='stSidebar'] { background-color: #100b1a !important; border-right: 1px solid rgba(147, 51, 234, 0.2); } [data-testid='stSidebar'] * { color: #ffffff !important; } div.stButton > button { background: linear-gradient(135deg, #a855f7 100%, #6366f1 0%) !important; color: #ffffff !important; border-radius: 8px; font-weight: 600; border: none; } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background-color: rgba(20, 15, 30, 0.85) !important; border: 1px solid rgba(168, 85, 247, 0.4) !important; border-radius: 8px; color: #ffffff !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: radial-gradient(circle at 20% 20%, #7928ca 0%, #312e81 50%, #0f172a 100%) !important; color: #ffffff !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #e2e8f0 !important; } h1, h2, h3, h4, h5, h6 { color: #f3e8ff !important; } [data-testid='stSidebar'] { background-color: #0f172a !important; border-right: 1px solid #7928ca; } [data-testid='stSidebar'] * { color: #ffffff !important; } div.stButton > button { background: linear-gradient(135deg, #7928ca 0%, #c084fc 100%) !important; color: #ffffff !important; border-radius: 8px; font-weight: 600; border: none; } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background-color: rgba(30, 27, 75, 0.7) !important; border: 1px solid #7928ca !important; border-radius: 8px; color: #ffffff !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: radial-gradient(circle at 70% 30%, #3b82f6 0%, #1e293b 50%, #090d16 100%) !important; color: #ffffff !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #cbd5e1 !important; } h1, h2, h3, h4, h5, h6 { color: #93c5fd !important; } [data-testid='stSidebar'] { background-color: #0b0f19 !important; border-right: 1px solid #3b82f6; } [data-testid='stSidebar'] * { color: #ffffff !important; } div.stButton > button { background: linear-gradient(135deg, #3b82f6 0%, #60a5fa 100%) !important; color: #ffffff !important; border-radius: 8px; font-weight: 600; border: none; } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background-color: rgba(15, 23, 42, 0.8) !important; border: 1px solid #3b82f6 !important; border-radius: 8px; color: #ffffff !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: radial-gradient(circle at 40% 40%, #059669 0%, #064e3b 50%, #022c22 100%) !important; color: #ffffff !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #d1fae5 !important; } h1, h2, h3, h4, h5, h6 { color: #6ee7b7 !important; } [data-testid='stSidebar'] { background-color: #022c22 !important; border-right: 1px solid #059669; } [data-testid='stSidebar'] * { color: #ffffff !important; } div.stButton > button { background: linear-gradient(135deg, #059669 0%, #34d399 100%) !important; color: #022c22 !important; border-radius: 8px; font-weight: 600; border: none; } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background-color: rgba(2, 44, 34, 0.8) !important; border: 1px solid #059669 !important; border-radius: 8px; color: #ffffff !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: radial-gradient(circle at 80% 20%, #d97706 0%, #78350f 50%, #1c1917 100%) !important; color: #ffffff !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #f5f5f4 !important; } h1, h2, h3, h4, h5, h6 { color: #fcd34d !important; } [data-testid='stSidebar'] { background-color: #1c1917 !important; border-right: 1px solid #d97706; } [data-testid='stSidebar'] * { color: #ffffff !important; } div.stButton > button { background: linear-gradient(135deg, #d97706 0%, #fbbf24 100%) !important; color: #1c1917 !important; border-radius: 8px; font-weight: 600; border: none; } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background-color: rgba(28, 25, 23, 0.85) !important; border: 1px solid #d97706 !important; border-radius: 8px; color: #ffffff !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: radial-gradient(circle at 30% 70%, #ec4899 0%, #8b5cf6 50%, #0f172a 100%) !important; color: #ffffff !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #fbcfe8 !important; } h1, h2, h3, h4, h5, h6 { color: #f472b6 !important; } [data-testid='stSidebar'] { background-color: #0f172a !important; border-right: 1px solid #ec4899; } [data-testid='stSidebar'] * { color: #ffffff !important; } div.stButton > button { background: linear-gradient(135deg, #ec4899 0%, #f43f5e 100%) !important; color: #ffffff !important; border-radius: 8px; font-weight: 600; border: none; } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background-color: rgba(15, 23, 42, 0.8) !important; border: 1px solid #ec4899 !important; border-radius: 8px; color: #ffffff !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: radial-gradient(circle at 60% 40%, #10b981 0%, #0284c7 50%, #030712 100%) !important; color: #ffffff !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #e2e8f0 !important; } h1, h2, h3, h4, h5, h6 { color: #38bdf8 !important; } [data-testid='stSidebar'] { background-color: #030712 !important; border-right: 1px solid #10b981; } [data-testid='stSidebar'] * { color: #ffffff !important; } div.stButton > button { background: linear-gradient(135deg, #10b981 0%, #06b6d4 100%) !important; color: #030712 !important; border-radius: 8px; font-weight: 600; border: none; } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background-color: rgba(3, 7, 18, 0.85) !important; border: 1px solid #10b981 !important; border-radius: 8px; color: #ffffff !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(180deg, #c7ecfd 0%, #f6f8e2 100%) !important; color: #2d3748 !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #4a5568 !important; } h1, h2, h3, h4, h5, h6 { color: #1a202c !important; } [data-testid='stSidebar'] { background-color: #e2eef6 !important; border-right: 1px solid #cbd5e1; } [data-testid='stSidebar'] * { color: #1a202c !important; } div.stButton > button { background: linear-gradient(135deg, #a5d8ff 0%, #bae6fd 100%) !important; color: #1e293b !important; border-radius: 8px; font-weight: 600; border: 1px solid #7dd3fc; } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background-color: rgba(255, 255, 255, 0.85) !important; border: 1px solid #bae6fd !important; border-radius: 8px; color: #1e293b !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(180deg, #d8b4fe 0%, #fbcfe8 100%) !important; color: #2d3748 !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #4a5568 !important; } h1, h2, h3, h4, h5, h6 { color: #581c87 !important; } [data-testid='stSidebar'] { background-color: #f3e8ff !important; border-right: 1px solid #d8b4fe; } [data-testid='stSidebar'] * { color: #581c87 !important; } div.stButton > button { background: linear-gradient(135deg, #c084fc 0%, #f472b6 100%) !important; color: #ffffff !important; border-radius: 8px; font-weight: 600; border: none; } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background-color: rgba(255, 255, 255, 0.85) !important; border: 1px solid #d8b4fe !important; border-radius: 8px; color: #1e293b !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(180deg, #fed7aa 0%, #fef08a 100%) !important; color: #2d3748 !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #451a03 !important; } h1, h2, h3, h4, h5, h6 { color: #78350f !important; } [data-testid='stSidebar'] { background-color: #fef3c7 !important; border-right: 1px solid #fed7aa; } [data-testid='stSidebar'] * { color: #78350f !important; } div.stButton > button { background: linear-gradient(135deg, #fb923c 0%, #facc15 100%) !important; color: #78350f !important; border-radius: 8px; font-weight: 600; border: none; } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background-color: rgba(255, 255, 255, 0.85) !important; border: 1px solid #fed7aa !important; border-radius: 8px; color: #1e293b !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(180deg, #fef08a 0%, #a7f3d0 100%) !important; color: #1e293b !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #334155 !important; } h1, h2, h3, h4, h5, h6 { color: #065f46 !important; } [data-testid='stSidebar'] { background-color: #ecfdf5 !important; border-right: 1px solid #a7f3d0; } [data-testid='stSidebar'] * { color: #065f46 !important; } div.stButton > button { background: linear-gradient(135deg, #facc15 0%, #34d399 100%) !important; color: #065f46 !important; border-radius: 8px; font-weight: 600; border: none; } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background-color: rgba(255, 255, 255, 0.85) !important; border: 1px solid #a7f3d0 !important; border-radius: 8px; color: #1e293b !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(180deg, #fbcfe8 0%, #a7f3d0 100%) !important; color: #1e293b !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #334155 !important; } h1, h2, h3, h4, h5, h6 { color: #831843 !important; } [data-testid='stSidebar'] { background-color: #fdf2f8 !important; border-right: 1px solid #fbcfe8; } [data-testid='stSidebar'] * { color: #831843 !important; } div.stButton > button { background: linear-gradient(135deg, #f472b6 0%, #34d399 100%) !important; color: #ffffff !important; border-radius: 8px; font-weight: 600; border: none; } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background-color: rgba(255, 255, 255, 0.85) !important; border: 1px solid #fbcfe8 !important; border-radius: 8px; color: #1e293b !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(180deg, #a7f3d0 0%, #fef08a 100%) !important; color: #1e293b !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #334155 !important; } h1, h2, h3, h4, h5, h6 { color: #065f46 !important; } [data-testid='stSidebar'] { background-color: #ecfdf5 !important; border-right: 1px solid #a7f3d0; } [data-testid='stSidebar'] * { color: #065f46 !important; } div.stButton > button { background: linear-gradient(135deg, #34d399 0%, #facc15 100%) !important; color: #065f46 !important; border-radius: 8px; font-weight: 600; border: none; } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background-color: rgba(255, 255, 255, 0.85) !important; border: 1px solid #a7f3d0 !important; border-radius: 8px; color: #1e293b !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(135deg, #a8edec 0%, #fed6e3 50%, #e2d1c3 100%) !important; color: #1e293b !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #334155 !important; } h1, h2, h3, h4, h5, h6 { color: #0f172a !important; } [data-testid='stSidebar'] { background: rgba(255, 255, 255, 0.4) !important; backdrop-filter: blur(12px); border-right: 1px solid rgba(255, 255, 255, 0.6); } [data-testid='stSidebar'] * { color: #1e293b !important; } div.stButton > button { background: rgba(255, 255, 255, 0.6) !important; backdrop-filter: blur(8px); color: #0f172a !important; border-radius: 12px; font-weight: 600; border: 1px solid rgba(255, 255, 255, 0.9); box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.1); } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background: rgba(255, 255, 255, 0.5) !important; backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.8) !important; border-radius: 12px; color: #1e293b !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(135deg, #84fab0 0%, #8fd3f4 50%, #d4b5fc 100%) !important; color: #1e293b !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #334155 !important; } h1, h2, h3, h4, h5, h6 { color: #0f172a !important; } [data-testid='stSidebar'] { background: rgba(255, 255, 255, 0.45) !important; backdrop-filter: blur(12px); border-right: 1px solid rgba(255, 255, 255, 0.6); } [data-testid='stSidebar'] * { color: #1e293b !important; } div.stButton > button { background: rgba(255, 255, 255, 0.65) !important; backdrop-filter: blur(8px); color: #0f172a !important; border-radius: 12px; font-weight: 600; border: 1px solid rgba(255, 255, 255, 0.9); box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.1); } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background: rgba(255, 255, 255, 0.55) !important; backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.8) !important; border-radius: 12px; color: #1e293b !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(135deg, #ff9a9e 0%, #fecfef 50%, #a1c4fd 100%) !important; color: #1e293b !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #334155 !important; } h1, h2, h3, h4, h5, h6 { color: #1e1b4b !important; } [data-testid='stSidebar'] { background: rgba(255, 255, 255, 0.45) !important; backdrop-filter: blur(12px); border-right: 1px solid rgba(255, 255, 255, 0.6); } [data-testid='stSidebar'] * { color: #1e293b !important; } div.stButton > button { background: rgba(255, 255, 255, 0.65) !important; backdrop-filter: blur(8px); color: #1e1b4b !important; border-radius: 12px; font-weight: 600; border: 1px solid rgba(255, 255, 255, 0.9); box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.1); } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background: rgba(255, 255, 255, 0.55) !important; backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.8) !important; border-radius: 12px; color: #1e293b !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 50%, #fbcfe8 100%) !important; color: #1e293b !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #334155 !important; } h1, h2, h3, h4, h5, h6 { color: #0f172a !important; } [data-testid='stSidebar'] { background: rgba(255, 255, 255, 0.45) !important; backdrop-filter: blur(12px); border-right: 1px solid rgba(255, 255, 255, 0.6); } [data-testid='stSidebar'] * { color: #1e293b !important; } div.stButton > button { background: rgba(255, 255, 255, 0.65) !important; backdrop-filter: blur(8px); color: #0f172a !important; border-radius: 12px; font-weight: 600; border: 1px solid rgba(255, 255, 255, 0.9); box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.1); } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background: rgba(255, 255, 255, 0.55) !important; backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.8) !important; border-radius: 12px; color: #1e293b !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(135deg, #ffecd2 0%, #fcb69f 50%, #a8ede 100%) !important; color: #1e293b !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #334155 !important; } h1, h2, h3, h4, h5, h6 { color: #7c2d12 !important; } [data-testid='stSidebar'] { background: rgba(255, 255, 255, 0.45) !important; backdrop-filter: blur(12px); border-right: 1px solid rgba(255, 255, 255, 0.6); } [data-testid='stSidebar'] * { color: #1e293b !important; } div.stButton > button { background: rgba(255, 255, 255, 0.65) !important; backdrop-filter: blur(8px); color: #7c2d12 !important; border-radius: 12px; font-weight: 600; border: 1px solid rgba(255, 255, 255, 0.9); box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.1); } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background: rgba(255, 255, 255, 0.55) !important; backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.8) !important; border-radius: 12px; color: #1e293b !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(135deg, #ff9a9e 0%, #fecfef 99%, #fecfef 100%) !important; color: #1e293b !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #334155 !important; } h1, h2, h3, h4, h5, h6 { color: #831843 !important; } [data-testid='stSidebar'] { background: rgba(255, 255, 255, 0.45) !important; backdrop-filter: blur(12px); border-right: 1px solid rgba(255, 255, 255, 0.6); } [data-testid='stSidebar'] * { color: #1e293b !important; } div.stButton > button { background: rgba(255, 255, 255, 0.65) !important; backdrop-filter: blur(8px); color: #831843 !important; border-radius: 12px; font-weight: 600; border: 1px solid rgba(255, 255, 255, 0.9); box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.1); } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background: rgba(255, 255, 255, 0.55) !important; backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.8) !important; border-radius: 12px; color: #1e293b !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(135deg, #00c6ff 0%, #0072ff 100%) !important; color: #ffffff !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #f1f5f9 !important; } h1, h2, h3, h4, h5, h6 { color: #ffffff !important; } [data-testid='stSidebar'] { background: rgba(15, 23, 42, 0.45) !important; backdrop-filter: blur(12px); border-right: 1px solid rgba(255, 255, 255, 0.2); } [data-testid='stSidebar'] * { color: #ffffff !important; } div.stButton > button { background: rgba(255, 255, 255, 0.2) !important; backdrop-filter: blur(8px); color: #ffffff !important; border-radius: 12px; font-weight: 600; border: 1px solid rgba(255, 255, 255, 0.4); box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.2); } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background: rgba(15, 23, 42, 0.4) !important; backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.3) !important; border-radius: 12px; color: #ffffff !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%) !important; color: #f8fafc !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #cbd5e1 !important; } h1, h2, h3, h4, h5, h6 { color: #f8fafc !important; } [data-testid='stSidebar'] { background: rgba(15, 23, 42, 0.6) !important; backdrop-filter: blur(12px); border-right: 1px solid rgba(255, 255, 255, 0.1); } [data-testid='stSidebar'] * { color: #f8fafc !important; } div.stButton > button { background: rgba(255, 255, 255, 0.1) !important; backdrop-filter: blur(8px); color: #f8fafc !important; border-radius: 12px; font-weight: 600; border: 1px solid rgba(255, 255, 255, 0.2); box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37); } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background: rgba(30, 41, 59, 0.5) !important; backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.15) !important; border-radius: 12px; color: #f8fafc !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(135deg, #022c22 100%, #064e3b 0%) !important; color: #f0fdf4 !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #a7f3d0 !important; } h1, h2, h3, h4, h5, h6 { color: #6ee7b7 !important; } [data-testid='stSidebar'] { background: rgba(2, 44, 34, 0.6) !important; backdrop-filter: blur(12px); border-right: 1px solid rgba(52, 211, 153, 0.2); } [data-testid='stSidebar'] * { color: #f0fdf4 !important; } div.stButton > button { background: rgba(52, 211, 153, 0.15) !important; backdrop-filter: blur(8px); color: #6ee7b7 !important; border-radius: 12px; font-weight: 600; border: 1px solid rgba(52, 211, 153, 0.3); box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37); } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background: rgba(6, 78, 59, 0.5) !important; backdrop-filter: blur(10px); border: 1px solid rgba(52, 211, 153, 0.2) !important; border-radius: 12px; color: #f0fdf4 !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(135deg, #2e1065 0%, #701a75 100%) !important; color: #fae8ff !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #f5d0fe !important; } h1, h2, h3, h4, h5, h6 { color: #f0abfc !important; } [data-testid='stSidebar'] { background: rgba(46, 16, 101, 0.6) !important; backdrop-filter: blur(12px); border-right: 1px solid rgba(240, 171, 252, 0.2); } [data-testid='stSidebar'] * { color: #fae8ff !important; } div.stButton > button { background: rgba(240, 171, 252, 0.15) !important; backdrop-filter: blur(8px); color: #f0abfc !important; border-radius: 12px; font-weight: 600; border: 1px solid rgba(240, 171, 252, 0.3); box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37); } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background: rgba(112, 26, 117, 0.5) !important; backdrop-filter: blur(10px); border: 1px solid rgba(240, 171, 252, 0.2) !important; border-radius: 12px; color: #fae8ff !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(135deg, #451a03 0%, #78350f 100%) !important; color: #fef3c7 !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #fde68a !important; } h1, h2, h3, h4, h5, h6 { color: #fcd34d !important; } [data-testid='stSidebar'] { background: rgba(69, 26, 3, 0.6) !important; backdrop-filter: blur(12px); border-right: 1px solid rgba(252, 211, 77, 0.2); } [data-testid='stSidebar'] * { color: #fef3c7 !important; } div.stButton > button { background: rgba(252, 211, 77, 0.15) !important; backdrop-filter: blur(8px); color: #fcd34d !important; border-radius: 12px; font-weight: 600; border: 1px solid rgba(252, 211, 77, 0.3); box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37); } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background: rgba(120, 53, 15, 0.5) !important; backdrop-filter: blur(10px); border: 1px solid rgba(252, 211, 77, 0.2) !important; border-radius: 12px; color: #fef3c7 !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(135deg, #e0f2fe 0%, #bae6fd 50%, #7dd3fc 100%) !important; color: #0f172a !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #334155 !important; } h1, h2, h3, h4, h5, h6 { color: #0369a1 !important; } [data-testid='stSidebar'] { background: rgba(255, 255, 255, 0.5) !important; backdrop-filter: blur(12px); border-right: 1px solid rgba(255, 255, 255, 0.7); } [data-testid='stSidebar'] * { color: #0f172a !important; } div.stButton > button { background: rgba(255, 255, 255, 0.7) !important; backdrop-filter: blur(8px); color: #0369a1 !important; border-radius: 12px; font-weight: 600; border: 1px solid rgba(255, 255, 255, 0.9); box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.1); } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background: rgba(255, 255, 255, 0.6) !important; backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.85) !important; border-radius: 12px; color: #0f172a !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(135deg, #fbcfe8 0%, #e9d5ff 50%, #fed7aa 100%) !important; color: #1e293b !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #334155 !important; } h1, h2, h3, h4, h5, h6 { color: #581c87 !important; } [data-testid='stSidebar'] { background: rgba(255, 255, 255, 0.5) !important; backdrop-filter: blur(12px); border-right: 1px solid rgba(255, 255, 255, 0.7); } [data-testid='stSidebar'] * { color: #1e293b !important; } div.stButton > button { background: rgba(255, 255, 255, 0.7) !important; backdrop-filter: blur(8px); color: #581c87 !important; border-radius: 12px; font-weight: 600; border: 1px solid rgba(255, 255, 255, 0.9); box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.1); } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background: rgba(255, 255, 255, 0.6) !important; backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.85) !important; border-radius: 12px; color: #1e293b !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: linear-gradient(135deg, #090d16 0%, #111b33 50%, #0d1527 100%) !important; color: #e2e8f0 !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #94a3b8 !important; } h1, h2, h3, h4, h5, h6 { color: #2dd4bf !important; text-shadow: 0 2px 10px rgba(45, 212, 191, 0.2); } [data-testid='stSidebar'] { background: rgba(13, 21, 39, 0.75) !important; backdrop-filter: blur(16px); border-right: 1px solid rgba(255, 255, 255, 0.08); } [data-testid='stSidebar'] * { color: #cbd5e1 !important; } div.stButton > button { background: rgba(30, 41, 59, 0.6) !important; backdrop-filter: blur(10px); color: #2dd4bf !important; border-radius: 10px; font-weight: 600; border: 1px solid rgba(45, 212, 191, 0.3); box-shadow: 0 4px 20px rgba(0, 0, 0, 0.4); } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background: rgba(17, 27, 51, 0.6) !important; backdrop-filter: blur(12px); border: 1px solid rgba(255, 255, 255, 0.1) !important; border-radius: 14px; color: #f8fafc !important; box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37); } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: radial-gradient(circle at 20% 20%, #7928ca 0%, #312e81 50%, #0f172a 100%) !important; color: #ffffff !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #e2e8f0 !important; } h1, h2, h3, h4, h5, h6 { color: #f3e8ff !important; } [data-testid='stSidebar'] { background-color: #0f172a !important; border-right: 1px solid #7928ca; } [data-testid='stSidebar'] * { color: #ffffff !important; } div.stButton > button { background: linear-gradient(135deg, #7928ca 0%, #c084fc 100%) !important; color: #ffffff !important; border-radius: 8px; font-weight: 600; border: none; } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background-color: rgba(30, 27, 75, 0.7) !important; border: 1px solid #7928ca !important; border-radius: 8px; color: #ffffff !important; } </style>", unsafe_allow_html=True) 
st.markdown("<style> .stApp { background: radial-gradient(circle at 70% 30%, #3b82f6 0%, #1e293b 50%, #090d16 100%) !important; color: #ffffff !important; } p, span, label, div[data-testid='stMarkdownContainer'] p { color: #cbd5e1 !important; } h1, h2, h3, h4, h5, h6 { color: #93c5fd !important; } [data-testid='stSidebar'] { background-color: #0b0f19 !important; border-right: 1px solid #3b82f6; } [data-testid='stSidebar'] * { color: #ffffff !important; } div.stButton > button { background: linear-gradient(135deg, #3b82f6 0%, #60a5fa 100%) !important; color: #ffffff !important; border-radius: 8px; font-weight: 600; border: none; } div[data-testid='stVerticalBlock'] > div > div > div[data-testid='stExpander'], .stTextInput input, div[data-testid='stFileUploader'] { background-color: rgba(15, 23, 42, 0.8) !important; border: 1px solid #3b82f6 !important; border-radius: 8px; color: #ffffff !important; } </style>", unsafe_allow_html=True)
